/* Generated by re2c 1.3 on Thu May 30 18:38:00 2024 */



#include <stdlib.h>
#include "ext_scanners.h"

bufsize_t _ext_scan_at(bufsize_t (*scanner)(const unsigned char *), unsigned char *ptr, int len, bufsize_t offset)
{
	bufsize_t res;

        if (ptr == NULL || offset >= len) {
          return 0;
        } else {
	  unsigned char lim = ptr[len];

	  ptr[len] = '\0';
	  res = scanner(ptr + offset);
	  ptr[len] = lim;
        }

	return res;
}



bufsize_t _scan_table_start(const unsigned char *p)
{
  const unsigned char *marker = NULL;
  const unsigned char *start = p;
  
{
  unsigned char yych;
  yych = *p;
  switch (yych) {
  case '\t':
  case '\v':
  case '\f':
  case ' ':
  case '|':  goto yy4;
  case '-':  goto yy5;
  case ':':  goto yy6;
  default:  goto yy2;
  }
yy2:
  ++p;
yy3:
  { return 0; }
yy4:
  yych = *(marker = ++p);
  switch (yych) {
  case '\t':
  case '\v':
  case '\f':
  case ' ':  goto yy7;
  case '-':  goto yy10;
  case ':':  goto yy12;
  default:  goto yy3;
  }
yy5:
  yych = *(marker = ++p);
  switch (yych) {
  case '\t':
  case '\n':
  case '\v':
  case '\f':
  case '\r':
  case ' ':
  case '|':  goto yy14;
  case '-':  goto yy10;
  case ':':  goto yy13;
  default:  goto yy3;
  }
yy6:
  yych = *(marker = ++p);
  switch (yych) {
  case '-':  goto yy10;
  default:  goto yy3;
  }
yy7:
  yych = *++p;
  switch (yych) {
  case '\t':
  case '\v':
  case '\f':
  case ' ':  goto yy7;
  case '-':  goto yy10;
  case ':':  goto yy12;
  default:  goto yy9;
  }
yy9:
  p = marker;
  goto yy3;
yy10:
  yych = *++p;
  switch (yych) {
  case '\t':
  case '\v':
  case '\f':
  case ' ':
  case ':':  goto yy13;
  case '\n':  goto yy15;
  case '\r':  goto yy17;
  case '-':  goto yy10;
  case '|':  goto yy18;
  default:  goto yy9;
  }
yy12:
  yych = *++p;
  switch (yych) {
  case '-':  goto yy10;
  default:  goto yy9;
  }
yy13:
  yych = *++p;
yy14:
  switch (yych) {
  case '\t':
  case '\v':
  case '\f':
  case ' ':  goto yy13;
  case '\n':  goto yy15;
  case '\r':  goto yy17;
  case '|':  goto yy18;
  default:  goto yy9;
  }
yy15:
  ++p;
  {
      return (bufsize_t)(p - start);
    }
yy17:
  yych = *++p;
  switch (yych) {
  case '\n':  goto yy15;
  default:  goto yy9;
  }
yy18:
  yych = *++p;
  switch (yych) {
  case '\t':
  case '\v':
  case '\f':
  case ' ':  goto yy18;
  case '\n':  goto yy15;
  case '\r':  goto yy17;
  case '-':  goto yy10;
  case ':':  goto yy12;
  default:  goto yy9;
  }
}

}

bufsize_t _scan_table_cell(const unsigned char *p)
{
  const unsigned char *marker = NULL;
  const unsigned char *start = p;
  
{
  unsigned char yych;
  yych = *p;
  switch (yych) {
  case '\n':
  case '\r':
  case '|':  goto yy25;
  case '\\':  goto yy27;
  default:  goto yy22;
  }
yy22:
  yych = *++p;
  switch (yych) {
  case '\n':
  case '\r':
  case '|':  goto yy24;
  case '\\':  goto yy27;
  default:  goto yy22;
  }
yy24:
  { return (bufsize_t)(p - start); }
yy25:
  ++p;
  { return 0; }
yy27:
  yych = *++p;
  switch (yych) {
  case '\n':
  case '\r':  goto yy24;
  case '\\':  goto yy27;
  default:  goto yy22;
  }
}

}

bufsize_t _scan_table_cell_end(const unsigned char *p)
{
  const unsigned char *start = p;
  
{
  unsigned char yych;
  yych = *p;
  switch (yych) {
  case '|':  goto yy33;
  default:  goto yy31;
  }
yy31:
  ++p;
  { return 0; }
yy33:
  yych = *++p;
  switch (yych) {
  case '\t':
  case '\v':
  case '\f':
  case ' ':  goto yy33;
  default:  goto yy35;
  }
yy35:
  { return (bufsize_t)(p - start); }
}

}

bufsize_t _scan_table_row_end(const unsigned char *p)
{
  const unsigned char *marker = NULL;
  const unsigned char *start = p;
  
{
  unsigned char yych;
  yych = *p;
  switch (yych) {
  case '\t':
  case '\v':
  case '\f':
  case ' ':  goto yy40;
  case '\n':  goto yy41;
  case '\r':  goto yy43;
  default:  goto yy38;
  }
yy38:
  ++p;
yy39:
  { return 0; }
yy40:
  yych = *(marker = ++p);
  switch (yych) {
  case '\t':
  case '\n':
  case '\v':
  case '\f':
  case '\r':
  case ' ':  goto yy45;
  default:  goto yy39;
  }
yy41:
  ++p;
  { return (bufsize_t)(p - start); }
yy43:
  yych = *++p;
  switch (yych) {
  case '\n':  goto yy41;
  default:  goto yy39;
  }
yy44:
  yych = *++p;
yy45:
  switch (yych) {
  case '\t':
  case '\v':
  case '\f':
  case ' ':  goto yy44;
  case '\n':  goto yy41;
  case '\r':  goto yy47;
  default:  goto yy46;
  }
yy46:
  p = marker;
  goto yy39;
yy47:
  yych = *++p;
  switch (yych) {
  case '\n':  goto yy41;
  default:  goto yy46;
  }
}

}

bufsize_t _scan_tasklist(const unsigned char *p)
{
  const unsigned char *marker = NULL;
  const unsigned char *start = p;
  
{
  unsigned char yych;
  yych = *p;
  switch (yych) {
  case '\t':
  case '\v':
  case '\f':
  case ' ':  goto yy52;
  case '*':
  case '+':
  case '-':  goto yy53;
  case '0':
  case '1':
  case '2':
  case '3':
  case '4':
  case '5':
  case '6':
  case '7':
  case '8':
  case '9':  goto yy54;
  default:  goto yy50;
  }
yy50:
  ++p;
yy51:
  { return 0; }
yy52:
  yych = *(marker = ++p);
  switch (yych) {
  case '\t':
  case '\v':
  case '\f':
  case ' ':  goto yy55;
  case '*':
  case '+':
  case '-':  goto yy58;
  case '0':
  case '1':
  case '2':
  case '3':
  case '4':
  case '5':
  case '6':
  case '7':
  case '8':
  case '9':  goto yy59;
  default:  goto yy51;
  }
yy53:
  yych = *(marker = ++p);
  switch (yych) {
  case '\t':
  case '\v':
  case '\f':
  case ' ':  goto yy60;
  default:  goto yy51;
  }
yy54:
  yych = *(marker = ++p);
  switch (yych) {
  case '\n':  goto yy51;
  case '0':
  case '1':
  case '2':
  case '3':
  case '4':
  case '5':
  case '6':
  case '7':
  case '8':
  case '9':  goto yy62;
  default:  goto yy58;
  }
yy55:
  yych = *++p;
  switch (yych) {
  case '\t':
  case '\v':
  case '\f':
  case ' ':  goto yy55;
  case '*':
  case '+':
  case '-':  goto yy58;
  case '0':
  case '1':
  case '2':
  case '3':
  case '4':
  case '5':
  case '6':
  case '7':
  case '8':
  case '9':  goto yy59;
  default:  goto yy57;
  }
yy57:
  p = marker;
  goto yy51;
yy58:
  yych = *++p;
  switch (yych) {
  case '[':  goto yy57;
  default:  goto yy61;
  }
yy59:
  yych = *++p;
  switch (yych) {
  case '\n':  goto yy57;
  case '0':
  case '1':
  case '2':
  case '3':
  case '4':
  case '5':
  case '6':
  case '7':
  case '8':
  case '9':  goto yy62;
  default:  goto yy58;
  }
yy60:
  yych = *++p;
yy61:
  switch (yych) {
  case '\t':
  case '\v':
  case '\f':
  case ' ':  goto yy60;
  case '[':  goto yy64;
  default:  goto yy57;
  }
yy62:
  yych = *++p;
  switch (yych) {
  case '\t':
  case '\v':
  case '\f':
  case ' ':  goto yy60;
  case '\n':  goto yy57;
  case '0':
  case '1':
  case '2':
  case '3':
  case '4':
  case '5':
  case '6':
  case '7':
  case '8':
  case '9':  goto yy62;
  default:  goto yy58;
  }
yy64:
  yych = *++p;
  switch (yych) {
  case ' ':
  case 'x':  goto yy65;
  default:  goto yy57;
  }
yy65:
  yych = *++p;
  switch (yych) {
  case ']':  goto yy66;
  default:  goto yy57;
  }
yy66:
  yych = *++p;
  switch (yych) {
  case '\t':
  case '\v':
  case '\f':
  case ' ':  goto yy67;
  default:  goto yy57;
  }
yy67:
  yych = *++p;
  switch (yych) {
  case '\t':
  case '\v':
  case '\f':
  case ' ':  goto yy67;
  default:  goto yy69;
  }
yy69:
  { return (bufsize_t)(p - start); }
}

}

bufsize_t _scan_math_start(const unsigned char *p)
{
  const unsigned char *marker = NULL;
  const unsigned char *start = p;
  
{
  unsigned char yych;
  yych = *p;
  switch (yych) {
  case '\t':
  case '\v':
  case '\f':
  case ' ':  goto yy74;
  case '$':  goto yy75;
  case '\\':  goto yy77;
  default:  goto yy72;
  }
yy72:
  ++p;
yy73:
  { return 0; }
yy74:
  yych = *(marker = ++p);
  switch (yych) {
  case '\t':
  case '\v':
  case '\f':
  case ' ':  goto yy78;
  case '$':  goto yy75;
  case '\\':  goto yy81;
  default:  goto yy73;
  }
yy75:
  yych = *++p;
  switch (yych) {
  case '$':  goto yy82;
  default:  goto yy76;
  }
yy76:
  { return (bufsize_t)(p - start); }
yy77:
  yych = *++p;
  switch (yych) {
  case '(':
  case '[':  goto yy82;
  default:  goto yy73;
  }
yy78:
  yych = *++p;
  switch (yych) {
  case '\t':
  case '\v':
  case '\f':
  case ' ':  goto yy78;
  case '$':  goto yy75;
  case '\\':  goto yy81;
  default:  goto yy80;
  }
yy80:
  p = marker;
  goto yy73;
yy81:
  yych = *++p;
  switch (yych) {
  case '(':
  case '[':  goto yy82;
  default:  goto yy80;
  }
yy82:
  ++p;
  goto yy76;
}

}

bufsize_t _scan_math_end(const unsigned char *p)
{
  const unsigned char *marker = NULL;
  const unsigned char *start = p;
  
{
  unsigned char yych;
  unsigned int yyaccept = 0;
  yych = *p;
  switch (yych) {
  case '\n':  goto yy87;
  case '$':  goto yy88;
  case '\\':  goto yy91;
  default:  goto yy85;
  }
yy85:
  yyaccept = 0;
  yych = *(marker = ++p);
  switch (yych) {
  case '\n':  goto yy86;
  default:  goto yy93;
  }
yy86:
  { return 0; }
yy87:
  ++p;
  goto yy86;
yy88:
  yyaccept = 1;
  yych = *(marker = ++p);
  switch (yych) {
  case '\t':
  case '\v':
  case '\f':
  case ' ':
  case '$':  goto yy88;
  case '\n':  goto yy90;
  case '\\':  goto yy95;
  default:  goto yy92;
  }
yy90:
  { return (bufsize_t)(p - start); }
yy91:
  yyaccept = 0;
  yych = *(marker = ++p);
  switch (yych) {
  case '\n':  goto yy86;
  case ')':
  case ']':  goto yy88;
  default:  goto yy93;
  }
yy92:
  yych = *++p;
yy93:
  switch (yych) {
  case '\n':  goto yy94;
  case '$':  goto yy88;
  case '\\':  goto yy95;
  default:  goto yy92;
  }
yy94:
  p = marker;
  if (yyaccept == 0) {
    goto yy86;
  } else {
    goto yy90;
  }
yy95:
  yych = *++p;
  switch (yych) {
  case '\n':  goto yy94;
  case '$':
  case ')':
  case ']':  goto yy88;
  case '\\':  goto yy95;
  default:  goto yy92;
  }
}

}